# Generated by Django 5.2.8 on 2025-11-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('keke', 'Keke'), ('car', 'Car'), ('taxi_bus', 'Taxi Bus'), ('bike', 'Bike')], max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
